apiVersion: v1
kind: Service
metadata:
  name: rdt-client
  labels:
    app: rdt-client
spec:
  type: ClusterIP
  ports:
    - port: 6500
      targetPort: 6500
      protocol: TCP
  selector:
    app: rdt-client
