apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rdt-client-data
  labels:
    app: rdt-client
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-2replicas-compressed-europe
