apiVersion: v1
kind: Service
metadata:
  name: ephemera
  labels:
    app.kubernetes.io/name: ephemera
spec:
  type: ClusterIP
  ports:
  - port: 8286
    targetPort: 8286
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: ephemera
