apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ephemera-data
  labels:
    app.kubernetes.io/name: ephemera
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replicas-us
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ephemera-downloads
  labels:
    app.kubernetes.io/name: ephemera
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replicas-us
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ephemera-ingest
  labels:
    app.kubernetes.io/name: ephemera
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replicas-us
  resources:
    requests:
      storage: 512Mi
