apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: stirling-pdf-data
      labels:
        app: stirling-pdf
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn-2replicas-us
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: stirling-pdf-configs
      labels:
        app: stirling-pdf
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn-2replicas-us
      resources:
        requests:
          storage: 100Mi
