apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf
  labels:
    app: stirling-pdf
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: stirling-pdf
