apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wealthfolio-data
  labels:
    app: wealthfolio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-2replicas-us
