apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  labels:
    app.kubernetes.io/name: blocky
data:
  config.yml: |
    upstreams:
      groups:
        default:
          - https://dns.quad9.net/dns-query
          - https://cloudflare-dns.com/dns-query
          - https://dns.google/dns-query

    conditional:
      mapping:
        cluster.local: 10.43.0.10
        svc.cluster.local: 10.43.0.10
        in-addr.arpa: 10.43.0.10
        ip6.arpa: 10.43.0.10

    blocking:
      blockType: zeroIp
      blockTTL: 1h
      denylists:
        default:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      clientGroupsBlock:
        default:
          - default
      loading:
        refreshPeriod: 24h

    prometheus:
      enable: true

    ports:
      dns: 53
      http: 4000
