apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  labels:
    app.kubernetes.io/name: blocky
data:
  config.yml: |
    bind_port: 53
    bind_addr: 0.0.0.0
    http_port: 4000
    prometheus: true

    upstreams:
      groups:
        default:
          - https://dns.quad9.net/dns-query
          - https://cloudflare-dns.com/dns-query
          - https://dns.google/dns-query

    conditional:
      mapping:
        cluster.local: ["10.43.0.10"]
        svc.cluster.local: ["10.43.0.10"]
        in-addr.arpa: ["10.43.0.10"]
        ip6.arpa: ["10.43.0.10"]

    blocking:
      blockType: zeroIp
      blockTTL: 1h
      refreshPeriod: 24h
      definitionFiles:
        - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      clientGroupsBlock:
        default:
          - default
