apiVersion: v1
kind: Service
metadata:
  name: netalertx
  labels:
    app: netalertx
spec:
  type: ClusterIP
  ports:
    - port: 20211
      targetPort: 20211
      protocol: TCP
  selector:
    app: netalertx
