apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netalertx-data
  labels:
    app: netalertx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-2replicas-us
