apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-bot
  namespace: monitoring
  labels:
    app.kubernetes.io/name: telegram-bot
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/component: alerting
spec:
  encryptedData:
    chat_id: AgDVB3VLfK+XhWUefu+qmSgl4a5BPysVhRIEiATVyIplDUtwRqK2hGrXCg0xXqTbaJ1pGW/5zNNVMAYCNFov0BM9w+/26lnspjOy1jwyIN6jC9Jb4CrQvb6k7WiDw2E1PY2UGyAasF/qnB9p/ChSa6N2/AHVhradWi0odGzcFr9qEJHviOj/mQtDK0E38g3/L4fxErw2AlmBetVCF1rrOcSWQjl76+phOV8cKStEBg2iObegxhxN9gABjLHjdfPy3C3Hbfx5KBnFGvEJM2ZkySxPGflSRH/2Tfzvclwzl/rivqDIkOcnz1ydWcebXjsWnFeNrYeyCZeAh4Oqoir/9asl4OG+sEpTnTRLdsI3VKH1K++Mi8ge9D4fZ22kETyNr9j47EbOie1mTppbgrpqYoKJEBdZLnaxvkTbN/3vai1SstpROqldK78IL8fgcWstR2CiNN5S7NaaWoHePVU6JvKnO+lo1H+coFlJRha+whe+lvi6VKg60uf4UraSu6i01iqtTE/QpRF1vT9URyejL53DhNa8B9vFnBRwc+tRPFDsU6lRDb0EggJx0K7aoKuSbr87A1Cdtkm833o4otQjF3dTyFQLhbd389rdpNuYMuEtc+QyvSHeIQbuOMMP9K0G9Aw3drJKQ/vcvvme90nLnpu067rZ5zzwWl01OCOPbMX6KHcfRRzAdAhTc7lyLDSR3tVLD6oAM6yrteBP
    token: AgAeCFE85yMwnAOocitCGeK7dxDDNNh59CFdfp5q+uim78kseggA9W3iaQ3rjJl0tzbZqfxXBryk1vSsKhfJg+SPjMczNf6TWttA3XNjzqleyym1PaJwvVHAZFac+bYLe/HUWiCwWzsq4ki8TnwWnOfvq4d2XOkiZHEXCDmbaJkRCnYr6RMlUkY1YzeKGDId938nRSivmGdSkUZgJAWYoaTqxsgnMr5tO7WLMOM7MZw68lYs5oaD3YlHpsach2OOjiet6G1MpqIxVUX673DQJgbuROLbRETL27Yxd6U3lBEb59PA2kgegN7FQHyKqOisEUkPlhzN/wmmegf0Myd2uOrJpeOU2GPZ2RmOjGN4jlV/YISDVVcNdMkaeBRkE6xxuvFMiBLwuyu4jxxeXAnIg5gm3zI2UYY/N+lyb2ApXTEPL8+KkoI457ix0kNjq27nNvg3hVm+M2pEz6cYehu4XL8vFPmG+ybnD2Ub4eWVcWVkHqlmcYzrzfPjXuYx9o2dDWye3Y7WJZj7lk48nYXA1LzLTfTHQf/J01/nZ9OPueNB3JrMQEAUSyGLPysCyU3ibCXHZQ0XWdSp/vxNFs9uf4zjM7ULjL6D0XKnuk/+02U/Ys2Vx5twzFQq/qmdPXzqh89hL/Q5OoP+qfvSDED+lfQXIOuzZqPDlsgYUMgZ8XaphgtS4fXyRvMMlFDo0SYa0N/VCiYvjO+hCbYsoNsWrIaAHBQuMNMUIEP+LSLVxVbZRrwR/Bam+N8Q+foSY06+
  template:
    metadata:
      name: telegram-bot
      namespace: monitoring
      labels:
        app.kubernetes.io/name: telegram-bot
        app.kubernetes.io/part-of: homelab
        app.kubernetes.io/component: alerting
    type: Opaque
