apiVersion: v1
kind: ConfigMap
metadata:
  name: nanobot-config-sample
  namespace: nanobot
  labels:
    app.kubernetes.io/name: nanobot
data:
  config.json: |
    {
      "agents": {
        "defaults": {
          "model": "llama3.2",
          "provider": "ollama"
        }
      },
      "providers": {
        "ollama": {
          "apiKey": null,
          "apiBase": "http://127.0.0.1:11434/v1"
        }
      }
    }
