apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replicas-compressed-us
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replicas-compressed-us
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-redis-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replicas-compressed-us
  resources:
    requests:
      storage: 2Gi
