apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-data
  labels:
    app: gatus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-2replicas-compressed-europe
