apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-bot
  namespace: gatus
  labels:
    app.kubernetes.io/name: telegram-bot
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/component: alerting
spec:
  encryptedData:
    chat_id: AgCUs8SYwMM66qopNEvZ+gf5pxXZcGm75KVeLwcAf8K6s2za3LU9dtFN2h2X+0EKo+j/WbAmai62+4+85jLBsxk4pZ9LxjPL4kJyfjz/8Il0imWTScwEUq4zF5xBOT9vm/P00z3mn6aHl+T4+V2b0539QzaHGb5vZfs7DdI3QqZ3DSmC33hPYJosSgXpInKtGchNEs7gat6g7eWTBn1YaSnr4lTUbQkkExHETMU46zc2CwcrH+pqP+N9QDDYKKK61HRl5ACsBibg3v1zvgIfb8l3jz78X+SIJyiTosBdW7p28SbJhWNLXtMWeSv3oPNAxOqBRdOIrdkBjKCUtgMZWL6IzIYdvcgrOS7vb5rVlx4NAOU+BITBwwQFOXmyI0hz93RsYrCiZQ/JinsQ3hJ/BSGEqMzVjRtDGI3bFM0Z8J8tMumhdIjZosanUoQXhYKwxf7xJyyQIAM+F2mwtoiNGEmgDrjFaeNMdezV8MJ1ElLxAOsWvtS5imt5WLIG1JQlBukByBg8QN5XifzzrBC1UeJxX/ggmS0LAlRhJ+0u3xRHeWzm4Wavj5o5YDTeKnIWIKGuSOpBrYRqUWKq8DX34CcFNizrpufmAcoagLKJANxloi/0+bsaRBiMb4WcDZolqnaforN+QH/FQuS+keS5gvv41Q0XeQ6qgyD0uOZK/Hg+SBiuvujSA0x0dL4GoGRZUzQlaKp4dAn0Uic8
    token: AgBo63AUY1KGbLSHaGIbEceo4yqIl9ocQnxtYnUc9PMs1ZmxCk8ron/PJwcq9+052Z9ny4OhNDwEb20MNa5Ob2quwboidWh4PlLTPWu36SegXTmcssGksBbMT9dQI4trMl5GFAiVDnlxGTNIs+9wbiVVG3P/XZWmfvyRhIwlVks7SpYYhBQDfza9f5WPlirCzEKA+m15XZNOknGkHgWZrXSATi2hTBSjo9CnJqypVdJ6iP7d9q4POC91jvxGXzMfrSxafJ6Q70JnpmKY0oQQLLwOWRq3CFRwnWbttRaVNCri2l09gY3ypf9/WzEWxPph1B6haCNZ2FaRPIsmAza5jL5PzdvZVzllGlWK/h8gavRKFPtO3FjrCcjmzdk9eyvDNWz9WF3o/eiTKVjZFnRs4xftL5fJLTvfwHl9aBi/LRUChvDPFk6XkHtrnd6tMkVQC6qA7Pwd57scF57rgVdbmz9NYMczoUKmc8vaE6H1GliEhtmDl4ZyptHuDkYfODBmxX3KrbVzi99yHwKeuq1Wi86HidgwjZSubikFhzlcJFRQKrDLHP9UY8U8vvm/Hby18IwNBNpm48XIMCB3eO3lxrosUJOBirAh4Cadl2+VObWtnDeImUp5hlw73HAHVGT1HFiHBCIZCu4wzT61v/8/dL1PzEoF3+vv6ihqSMUPsFAuES/bL4X/Du4rjLs3xC+qzF0RYqhlxFZsyaLl1qQyz+qW5UjB1TqsSbBuQIL6Tx94egY+z5PYodoUMuDSLx6P
  template:
    metadata:
      name: telegram-bot
      namespace: gatus
      labels:
        app.kubernetes.io/name: telegram-bot
        app.kubernetes.io/part-of: homelab
        app.kubernetes.io/component: alerting
    type: Opaque
