apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: calibre-web-config
      labels:
        app: calibre-web
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: longhorn-2replicas-compressed
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: calibre-web-library
      labels:
        app: calibre-web
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: longhorn-2replicas-compressed
