apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web
  labels:
    app: calibre-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      labels:
        app: calibre-web
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - europe
      containers:
        - name: calibre-web
          image: crocodilestick/calibre-web-automated:V3.1.4
          ports:
            - containerPort: 8083
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Zurich
            - name: DOCKER_MODS
              value: linuxserver/mods:universal-calibre
          volumeMounts:
            - name: config
              mountPath: /config
            - name: library
              mountPath: /calibre-library
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 60
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: calibre-web-config
        - name: library
          persistentVolumeClaim:
            claimName: calibre-web-library
