apiVersion: v1
kind: Service
metadata:
  name: calibre-web
  labels:
    app: calibre-web
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app: calibre-web
