apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: paperless-data
      labels:
        app: paperless
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: longhorn-2replicas-compressed
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: paperless-media
      labels:
        app: paperless
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn-2replicas
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: paperless-export
      labels:
        app: paperless
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: longhorn-2replicas-compressed
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: paperless-consume
      labels:
        app: paperless
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: longhorn-2replicas-compressed
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: paperless-postgres
      labels:
        app: paperless
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: longhorn-2replicas-compressed
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: paperless-redis
      labels:
        app: paperless
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: longhorn-2replicas-compressed
