apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: paperless-web
      labels:
        app: paperless
        component: web
    spec:
      type: ClusterIP
      ports:
        - port: 8000
          targetPort: 8000
          protocol: TCP
      selector:
        app: paperless
  - apiVersion: v1
    kind: Service
    metadata:
      name: paperless-postgres
      labels:
        app: paperless
        component: postgres
    spec:
      type: ClusterIP
      ports:
        - port: 5432
          targetPort: 5432
          protocol: TCP
      selector:
        app: paperless
        component: postgres
  - apiVersion: v1
    kind: Service
    metadata:
      name: paperless-redis
      labels:
        app: paperless
        component: redis
    spec:
      type: ClusterIP
      ports:
        - port: 6379
          targetPort: 6379
          protocol: TCP
      selector:
        app: paperless
        component: redis
  - apiVersion: v1
    kind: Service
    metadata:
      name: paperless-gotenberg
      labels:
        app: paperless
        component: gotenberg
    spec:
      type: ClusterIP
      ports:
        - port: 3000
          targetPort: 3000
          protocol: TCP
      selector:
        app: paperless
        component: gotenberg
  - apiVersion: v1
    kind: Service
    metadata:
      name: paperless-tika
      labels:
        app: paperless
        component: tika
    spec:
      type: ClusterIP
      ports:
        - port: 9998
          targetPort: 9998
          protocol: TCP
      selector:
        app: paperless
        component: tika
