apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: paperless-redis
      labels:
        app: paperless
        component: redis
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: paperless
          component: redis
      template:
        metadata:
          labels:
            app: paperless
            component: redis
         spec:
           affinity:
             nodeAffinity:
               preferredDuringSchedulingIgnoredDuringExecution:
                 - weight: 100
                   preference:
                     matchExpressions:
                       - key: region
                         operator: In
                         values:
                           - us
           containers:
            - name: redis
              image: docker.io/library/redis:8
              ports:
                - containerPort: 6379
              resources:
                requests:
                  cpu: 25m
                  memory: 64Mi
                limits:
                  memory: 256Mi
              volumeMounts:
                - name: redisdata
                  mountPath: /data
              args: ["--save", "60", "1", "--loglevel", "warning"]
          volumes:
            - name: redisdata
              persistentVolumeClaim:
                claimName: paperless-redis
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: paperless-postgres
      labels:
        app: paperless
        component: postgres
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: paperless
          component: postgres
      template:
        metadata:
          labels:
            app: paperless
            component: postgres
         spec:
           affinity:
             nodeAffinity:
               preferredDuringSchedulingIgnoredDuringExecution:
                 - weight: 100
                   preference:
                     matchExpressions:
                       - key: region
                         operator: In
                         values:
                           - us
           containers:
            - name: postgres
              image: docker.io/library/postgres:18
              ports:
                - containerPort: 5432
              envFrom:
                - secretRef:
                    name: paperless-postgres
              env:
                - name: PGDATA
                  value: /var/lib/postgresql/data/pgdata
              volumeMounts:
                - name: pgdata
                  mountPath: /var/lib/postgresql/data
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
                limits:
                  memory: 512Mi
          volumes:
            - name: pgdata
              persistentVolumeClaim:
                claimName: paperless-postgres
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: paperless-gotenberg
      labels:
        app: paperless
        component: gotenberg
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: paperless
          component: gotenberg
      template:
        metadata:
          labels:
            app: paperless
            component: gotenberg
         spec:
           affinity:
             nodeAffinity:
               preferredDuringSchedulingIgnoredDuringExecution:
                 - weight: 100
                   preference:
                     matchExpressions:
                       - key: region
                         operator: In
                         values:
                           - us
           containers:
            - name: gotenberg
              image: docker.io/gotenberg/gotenberg:8.24
              ports:
                - containerPort: 3000
              command:
                - "gotenberg"
                - "--chromium-disable-javascript=true"
                - "--chromium-allow-list=file:///tmp/.*"
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  memory: 512Mi
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: paperless-tika
      labels:
        app: paperless
        component: tika
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: paperless
          component: tika
      template:
        metadata:
          labels:
            app: paperless
            component: tika
         spec:
           affinity:
             nodeAffinity:
               preferredDuringSchedulingIgnoredDuringExecution:
                 - weight: 100
                   preference:
                     matchExpressions:
                       - key: region
                         operator: In
                         values:
                           - us
           containers:
            - name: tika
              image: docker.io/apache/tika:latest
              ports:
                - containerPort: 9998
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
                limits:
                  memory: 512Mi
