apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: 1.11.0
      helm:
        valuesObject:
          defaultSettings:
            defaultReplicaCount: 2
            backupTarget: "s3://longhorn-backups-ay76@s3.eu-central-003/"
            backupTargetCredentialSecret: "k3s-longhorn-backup-backblaze"
          persistence:
            defaultClassReplicaCount: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
