apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: surfsense-data
  labels:
    app: surfsense
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-2replicas-compressed-us
