apiVersion: v1
kind: Service
metadata:
  name: surfsense-frontend
  labels:
    app: surfsense
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: surfsense
---
apiVersion: v1
kind: Service
metadata:
  name: surfsense-backend
  labels:
    app: surfsense
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: surfsense
