apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stacks-config
  labels:
    app: stacks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn-2replicas-europe
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stacks-logs
  labels:
    app: stacks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn-2replicas-europe
