apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: sabnzbd-config
      labels:
        app: sabnzbd
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: longhorn-2replicas-compressed
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: sabnzbd-downloads
      labels:
        app: sabnzbd
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 400Gi
      storageClassName: local-path
