apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data
  labels:
    app: couchdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-2replicas-compressed-us
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-config
  labels:
    app: couchdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn-2replicas-compressed-us
