apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stremio-data
  labels:
    app: stremio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-2replicas
