apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: docspell-restserver
      labels:
        app: docspell
        component: restserver
    spec:
      type: ClusterIP
      ports:
        - port: 7880
          targetPort: 7880
          protocol: TCP
      selector:
        app: docspell
        component: restserver
  - apiVersion: v1
    kind: Service
    metadata:
      name: docspell-joex
      labels:
        app: docspell
        component: joex
    spec:
      type: ClusterIP
      ports:
        - port: 7878
          targetPort: 7878
          protocol: TCP
      selector:
        app: docspell
        component: joex
  - apiVersion: v1
    kind: Service
    metadata:
      name: docspell-postgres
      labels:
        app: docspell
        component: postgres
    spec:
      type: ClusterIP
      ports:
        - port: 5432
          targetPort: 5432
          protocol: TCP
      selector:
        app: docspell
        component: postgres
  - apiVersion: v1
    kind: Service
    metadata:
      name: docspell-solr
      labels:
        app: docspell
        component: solr
    spec:
      type: ClusterIP
      ports:
        - port: 8983
          targetPort: 8983
          protocol: TCP
      selector:
        app: docspell
        component: solr
