- hostname: ssh_openstick.bosscher.ch
  service: ssh://localhost:22
- hostname: fusion_openstick.bosscher.ch
  service: http://localhost:8080
- hostname: gatus_openstick.bosscher.ch
  service: http://localhost:8081
- hostname: pico_openstick.bosscher.ch
  service: http://localhost:18800
- hostname: dozzle_openstick.bosscher.ch
  service: http://localhost:8888
- hostname: beszel_openstick.bosscher.ch
  service: http://localhost:8090
