apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: calibre-web-config
      namespace: books
      labels:
        app: calibre-web
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: longhorn-2replicas-compressed-europe
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: calibre-web-library
      namespace: books
      labels:
        app: calibre-web
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: longhorn-2replicas-compressed-europe
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: calibre-web-ingest
      namespace: books
      labels:
        app: calibre-web
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
      storageClassName: longhorn-2replicas-compressed-europe
