apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelfmark-config
  namespace: books
  labels:
    app: shelfmark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-2replicas-europe
