apiVersion: v1
kind: Service
metadata:
  name: stacks
  namespace: books
  labels:
    app: stacks
spec:
  type: ClusterIP
  ports:
    - port: 7788
      targetPort: 7788
      protocol: TCP
  selector:
    app: stacks
