apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fusion
  labels:
    app: fusion
spec:
  serviceName: "fusion"
  replicas: 1
  selector:
    matchLabels:
      app: fusion
  template:
    metadata:
      labels:
        app: fusion
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - bazzite
      containers:
        - name: fusion
          image: ghcr.io/0x2e/fusion:0.9.8
          ports:
            - containerPort: 8080
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fusion-secret
                  key: password
          volumeMounts:
            - name: fusion-data
              mountPath: /data
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: fusion-data
        labels:
          app: fusion
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "longhorn-2replicas-europe"
        resources:
          requests:
            storage: 2Gi
