apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fusion-data
  labels:
    app: fusion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-2replicas-europe
