apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kite-data
  labels:
    app: kite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-2replicas-compressed-europe
