---
- name: Check if k9s is already installed
  ansible.builtin.command: k9s version
  register: k9s_check
  failed_when: false
  changed_when: false
  tags: [k9s]

- name: Download and install k9s
  block:
    - name: Download k9s
      ansible.builtin.get_url:
        url: https://github.com/derailed/k9s/releases/download/v0.30.0/k9s_Linux_amd64.tar.gz
        dest: /tmp/k9s_Linux_amd64.tar.gz
        mode: "0644"
      become: true

    - name: Extract k9s
      ansible.builtin.unarchive:
        src: /tmp/k9s_Linux_amd64.tar.gz
        dest: /tmp
        remote_src: true
      become: true

    - name: Move k9s to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/k9s
        dest: /usr/local/bin/k9s
        mode: "0755"
        remote_src: true
      become: true

    - name: Clean up k9s files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/k9s_Linux_amd64.tar.gz
        - /tmp/k9s
        - /tmp/LICENSE
        - /tmp/README.md
      become: true
  when: k9s_check.rc != 0
  tags: [k9s]