apiVersion: v1
kind: Service
metadata:
  name: listenarr
  labels:
    app: listenarr
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: listenarr
