apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: your-spotify-mongo-data
  labels:
    app: your-spotify
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: longhorn-2replicas-us
