apiVersion: v1
kind: Service
metadata:
  name: technitium
  labels:
    app: technitium
spec:
  type: ClusterIP
  selector:
    app: technitium
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: web
      port: 5380
      targetPort: 5380
      protocol: TCP
