apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-config
  labels:
    app: technitium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-2replicas-compressed
