apiVersion: v1
kind: Service
metadata:
  name: technitium
  labels:
    app: technitium
spec:
  type: ClusterIP
  selector:
    app: technitium
  ports:
    - name: DNS-over-HTTP
      port: 80
      targetPort: 80
      protocol: TCP
