apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nullclaw-pvc
  labels:
    app.kubernetes.io/name: nullclaw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replicas-europe
  resources:
    requests:
      storage: 2Gi
