---
- name: Apply shared roles to all nodes
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: Update dnf cache
      ansible.builtin.dnf:
        update_cache: yes
      tags: [always]

    - name: Select cluster network interface
      ansible.builtin.set_fact:
        cluster_network_interface: >-
          {{ 'eth0' if 'eth0' in ansible_facts.interfaces else ('ens192' if 'ens192' in ansible_facts.interfaces else ansible_facts.default_ipv4.interface) }}
      tags: [always]

    - name: Set network interface IPs
      ansible.builtin.set_fact:
        tailscale_ip: "{{ ansible_facts.get('tailscale0', {}).get('ipv4', {}).get('address', ansible_facts.default_ipv4.address) }}"
        cluster_network_ip: "{{ ansible_facts.get(cluster_network_interface, {}).get('ipv4', {}).get('address', ansible_facts.default_ipv4.address) }}"
      tags: [always]

  roles:
    - { role: security_updates }
    - { role: system-hardening }
    - { role: dotfiles }
    - { role: tools }
    - { role: iscsid }
    - { role: k9s }
    - { role: optimizations }
    - { role: network-optimizations }
    - { role: tailscale }
    - { role: kubecolor }
    - { role: zram }
    - { role: ssh }
    - { role: crowdsec }
    - { role: k3s-oom-protection }
    - { role: k3s-install }
    - { role: firewall }

- name: Kubernetes control plane configuration
  hosts: kubernetes_control_plane
  serial: 1
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - { role: k3s-common }
    - { role: kubernetes-control-plane }
    - { role: etcd-io-priority }
    - { role: etcd-maintenance }

- name: Kubernetes agent node configuration
  hosts: kubernetes_agent
  serial: 1
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - { role: k3s-common }
    - { role: kubernetes-agent }
