apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag-redis
  labels:
    app: wallabag
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
      component: redis
  template:
    metadata:
      labels:
        app: wallabag
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: wallabag-redis
  labels:
    app: wallabag
    component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: wallabag
    component: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag-db
  labels:
    app: wallabag
    component: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
      component: db
  template:
    metadata:
      labels:
        app: wallabag
        component: db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: wallabag
            - name: POSTGRES_USER
              value: wallabag
            - name: POSTGRES_PASSWORD
              value: wallabag
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: wallabag-db
---
apiVersion: v1
kind: Service
metadata:
  name: wallabag-db
  labels:
    app: wallabag
    component: db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: wallabag
    component: db
