apiVersion: v1
kind: Service
metadata:
  name: aiometadata
  labels:
    app: aiometadata
spec:
  ports:
    - port: 3232
      targetPort: 3232
      protocol: TCP
      name: http
  selector:
    app: aiometadata
