apiVersion: v1
kind: Service
metadata:
  name: aiometadata-redis
  labels:
    app.kubernetes.io/name: aiometadata-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: aiometadata-redis
