apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: audiobookshelf-config
      labels:
        app: audiobookshelf
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: longhorn-2replicas-compressed-europe
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: audiobookshelf-metadata
      labels:
        app: audiobookshelf
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: longhorn-2replicas-compressed-europe
