apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opencode
  labels:
    app.kubernetes.io/name: opencode
spec:
  serviceName: opencode
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opencode
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opencode
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - europe
      containers:
        - name: opencode
          image: ghcr.io/laurensbosscher/opencode:latest
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 4096
              protocol: TCP
          workingDir: /home/bun/workspaces
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 4096Mi
          livenessProbe:
            httpGet:
              path: /global/health
              port: 4096
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /global/health
              port: 4096
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 5
          volumeMounts:
            - name: opencode-data
              mountPath: /home/bun/workspaces
            - name: tmp
              mountPath: /tmp
            - name: opencode-config
              mountPath: /home/bun/.local/share/opencode
      volumes:
        - name: tmp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: opencode-data
        labels:
          app.kubernetes.io/name: opencode
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn-2replicas-europe"
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: opencode-config
        labels:
          app.kubernetes.io/name: opencode
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn-2replicas-europe"
        resources:
          requests:
            storage: 512Mi
