apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: default
spec:
  limits:
    # Default limits for containers if not specified
    - type: Container
      default:
        cpu: 1000m
        memory: 1Gi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: 8000m
        memory: 32Gi
      min:
        cpu: 10m
        memory: 32Mi
    # Limits for pods
    - type: Pod
      max:
        cpu: 16000m
        memory: 64Gi
      min:
        cpu: 10m
        memory: 32Mi
    # Limits for PVCs
    - type: PersistentVolumeClaim
      max:
        storage: 1Ti
      min:
        storage: 1Gi
