apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-2replicas-us
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  # If possible, store the data locally on the node where the pod is scheduled
  dataLocality: "best-effort"
  nodeDownPodDeletionPolicy: "Delete"
  staleReplicaTimeout: "30"
  fromBackup: ""
  # Compress backups
  backup.compression: "lz4"
  backup.deduplication: "true"
nodeSelector: "us"
