apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-resource-quota
  namespace: default
spec:
  hard:
    # Limit total CPU and memory requests/limits across all pods
    requests.cpu: "50"
    requests.memory: 100Gi
    limits.cpu: "100"
    limits.memory: 200Gi
    # Limit number of resources
    pods: "100"
    services: "50"
    persistentvolumeclaims: "50"
    secrets: "100"
    configmaps: "100"
