apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replicas-compressed-us
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replicas-compressed-us
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-meili-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replicas-compressed-us
  resources:
    requests:
      storage: 1Gi
