apiVersion: v1
kind: Service
metadata:
  name: linkwarden-postgres
spec:
  selector:
    app: linkwarden-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: linkwarden-meilisearch
spec:
  selector:
    app: linkwarden-meilisearch
  ports:
    - protocol: TCP
      port: 7700
      targetPort: 7700
---
apiVersion: v1
kind: Service
metadata:
  name: linkwarden
spec:
  selector:
    app: linkwarden
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http