apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-postgres-data
  labels:
    app: linkwarden-postgres
    app.kubernetes.io/name: linkwarden
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replicas-compressed-europe
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-meili-data
  labels:
    app: linkwarden-meilisearch
    app.kubernetes.io/name: linkwarden
    app.kubernetes.io/component: search
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replicas-compressed-europe
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-data
  labels:
    app: linkwarden
    app.kubernetes.io/name: linkwarden
    app.kubernetes.io/component: app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replicas-compressed-europe
  resources:
    requests:
      storage: 10Gi
