apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shiori-data
  labels:
    app: shiori
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-2replicas-compressed-us
