apiVersion: v1
kind: Service
metadata:
  name: flaresolver
  namespace: flaresolver
  labels:
    app.kubernetes.io/name: flaresolver
    app.kubernetes.io/part-of: homelab
spec:
  selector:
    app: flaresolver
  ports:
    - port: 8191
      targetPort: 8191
      name: http
