apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: 1.10.1 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          image:
            longhorn:
              manager:
                # Override only the manager image tag (keep repository default)
                tag: v1.10.0-hotfix-1
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
