apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aiostreams-data
  labels:
    app: aiostreams
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-2replicas-europe
