apiVersion: v1
kind: Service
metadata:
  name: aiostreams
  labels:
    app: aiostreams
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: aiostreams
