apiVersion: v1
kind: Service
metadata:
  name: bentopdf
  labels:
    app: bentopdf
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: bentopdf
