apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: weekly-fstrim
  namespace: longhorn-system
spec:
  name: weekly-fstrim
  cron: 0 2 * * 0
  task: filesystem-trim
  groups:
    - default
  retain: 0
  concurrency: 1
