# Generated by Django 6.0.1 on 2026-01-10 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_scan_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scanning", "Scanning"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="scanner.host",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PortScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.IntegerField()),
                ("protocol", models.CharField(default="tcp", max_length=10)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("filtered", "Filtered"),
                        ],
                        max_length=20,
                    ),
                ),
                ("service_name", models.CharField(blank=True, max_length=100)),
                ("service_version", models.CharField(blank=True, max_length=255)),
                (
                    "scan_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        to="scanner.scanresult",
                    ),
                ),
            ],
            options={
                "ordering": ["port"],
            },
        ),
        migrations.AddIndex(
            model_name="scanresult",
            index=models.Index(
                fields=["host", "-started_at"], name="scanner_sca_host_id_af0369_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portscan",
            index=models.Index(
                fields=["scan_result", "state"], name="scanner_por_scan_re_a1b454_idx"
            ),
        ),
    ]
