apiVersion: v1
kind: Service
metadata:
  name: perplexica
  labels:
    app: perplexica
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: perplexica
