apiVersion: v1
kind: Service
metadata:
  name: perplexica-searxng
  labels:
    app: perplexica-searxng
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: perplexica-searxng
