apiVersion: v1
kind: Service
metadata:
  name: clawdbot
  labels:
    app: clawdbot
spec:
  type: ClusterIP
  ports:
    - port: 18789
      targetPort: 18789
      protocol: TCP
      name: gateway
    - port: 18790
      targetPort: 18790
      protocol: TCP
      name: bridge
  selector:
    app: clawdbot
