apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clawdbot-config
  labels:
    app: clawdbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-2replicas-compressed-us
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clawdbot-workspace
  labels:
    app: clawdbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-2replicas-compressed-us
