apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-from-helm-charts
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/LaurensBosscher/homelab.git
        revision: main
        directories:
          - path: helm/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/LaurensBosscher/homelab.git
        targetRevision: main
        path: "{{path}}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
