apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
spec:
  encryptedData:
    telegram-token: AgCdcB9HjUkyZbNFyTx5Qe+Uee+77a3CW4S4/9q424Z9FBjelCt04v75lsdqhVTGqA5q1MbtmBQivILNsv+fHrpG7U5yelzasPK54W9Qqmgz8DMneRLcJNsjNfnxzU1coLl/XvGuQR+kOt5F21mj9QDYE+9Bhj4Inb/KkEoM+U7HD6AhfmIadvWfQaz6s1fw+WMAO687x691Keb3Ikj9sLcA77CJpzoBNJnP9u1p0jYaI9K8+aic3g02UDR7dBi42wbqCc8rkEuXQpnF6FLx5CR0nUwsV9Hl0dda7OamFSiIh7LzSDdhaZRVfb2WWtfFZ3L7BcUjq83CH1io0IJ6OhwH0ZVTHnuF6Q8e06E2bPYMUeG72pukMxeTCvnHZ+Nc6H4CI5fMPax1wljm7uMktBFJxenUzLCGQnmoPjZqLqMMQyqYDKPOCmpPlU0IM6SHvSGstpi4x6ub1cR3PXo7b19oChI7eIbqheeRsU91UGMOIEHBbuPBjJERjL6SIyAg8kl5jVSHm0H+tOKHi+/L0eLzc0N61tpQEwqFjfe8hEIAtRhc3+DwWvGuPTbRAR3wnC6dKA814930rawuPveyylifXTCSBIucb+BGKAsY8e4RzqjwBGhI9nuO2a0xEnsFZe4r//uHjJ4zxhoCKLicnfVRTVpZmuTSwAK4K0E0QVZsOXQHfbIKB3Cw2Z9dPW/0vukX1ltNM17Bte0iLLJnZw5tojCZwMs+Nv/XbOpPNMYsHgK2ixQHK0mt1zflDgIZ
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
      labels:
        app.kubernetes.io/component: notifications-controller
        app.kubernetes.io/name: argocd-notifications-controller
        app.kubernetes.io/part-of: argocd
    type: Opaque
